name: Zouthedog
favicon: null
layout_spectrum: 0.9865735
typography_spectrum: 0.6750805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1E1F1F'
    - '#DFEAF3'
    - '#80B4E1'
    - '#5D8FC7'
    - '#1D4C76'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
