layout_spectrum: 0.9865735
typography_spectrum: 0.6750805
color:
  saturation: 0.5755558
  lightness: 0.8315351
  brandStrength: 0.2569511
  brandColors:
    - '#1E1F1F'
    - '#DFEAF3'
    - '#80B4E1'
    - '#5D8FC7'
    - '#1D4C76'
  rhythmicContrast: 0.1262084
name: Zouthedog
